/*
 * Copyright (c) 2024 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://docs.edgeimpulse.com/page/terms-of-service) or Enterprise Terms of
 * Service (https://docs.edgeimpulse.com/page/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 13, 26 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 1383.0467956934344, 1790.861716422848, 1596.6861368582547 };
const float ei_classifier_anom_mean[3] = { 1708.3572905297374, 1870.1453279358109, 4138.98941179662 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[32] = {
	{ ( float[3] ) { 1.1904643774032593, -0.4878762364387512, -0.6537564992904663 }, 0.19219715957330613 },
	{ ( float[3] ) { -1.1184228658676147, -1.0129754543304443, -0.6984946727752686 }, 0.059996639873738614 },
	{ ( float[3] ) { -0.20170018076896667, 0.8267475962638855, 0.7407901883125305 }, 0.37305680687865583 },
	{ ( float[3] ) { 0.026571210473775864, 1.6403802633285522, 1.5027281045913696 }, 0.25170648725080963 },
	{ ( float[3] ) { -0.31984713673591614, 1.0580971240997314, 1.341968297958374 }, 0.21150397535068846 },
	{ ( float[3] ) { 0.868402361869812, -0.47747352719306946, -0.6653367280960083 }, 0.20172726374562583 },
	{ ( float[3] ) { 0.43496790528297424, 1.7607226371765137, 2.3228588104248047 }, 0.37434662102477884 },
	{ ( float[3] ) { -0.3332047462463379, 1.2610067129135132, 1.007265329360962 }, 0.17619484195127808 },
	{ ( float[3] ) { 0.5028728246688843, -0.5374142527580261, -0.67399001121521 }, 0.3399469192814488 },
	{ ( float[3] ) { 0.6304592490196228, -0.016464509069919586, -0.6607784628868103 }, 0.21847054795521292 },
	{ ( float[3] ) { 0.10286666452884674, 1.9482048749923706, 1.7321815490722656 }, 0.1742702794163004 },
	{ ( float[3] ) { 1.4162371158599854, -0.512630820274353, -0.6612942814826965 }, 0.10354890474716434 },
	{ ( float[3] ) { -0.3389878571033478, 0.6471207737922668, 1.1675872802734375 }, 0.1980987022923044 },
	{ ( float[3] ) { 1.3402727842330933, 0.012996502220630646, -0.6672567129135132 }, 0.14172478011026052 },
	{ ( float[3] ) { 0.12334130704402924, 1.2979222536087036, 1.4155634641647339 }, 0.25434747186165635 },
	{ ( float[3] ) { 1.5652607679367065, 0.02100748009979725, -0.6301031708717346 }, 0.11598857935358471 },
	{ ( float[3] ) { 1.6694692373275757, -0.29215100407600403, -0.6600236296653748 }, 0.18186778695963618 },
	{ ( float[3] ) { 0.056878551840782166, 1.5258800983428955, 2.090181827545166 }, 0.214397650347618 },
	{ ( float[3] ) { 1.971775770187378, -0.00787689071148634, -0.6149647235870361 }, 0.30366756264625416 },
	{ ( float[3] ) { -0.44591614603996277, 0.24914789199829102, 0.12784098088741302 }, 1.4901161193847656e-8 },
	{ ( float[3] ) { 0.13010305166244507, 0.9349541664123535, 2.241274833679199 }, 0.11896939413601278 },
	{ ( float[3] ) { 0.1963501274585724, -0.029289765283465385, -0.667646586894989 }, 0.11456950977114952 },
	{ ( float[3] ) { 0.1835917979478836, 1.15746009349823, 2.0696380138397217 }, 0.1750116407768575 },
	{ ( float[3] ) { -0.143964022397995, 1.2119017839431763, 0.5549699664115906 }, 0.12643678651335 },
	{ ( float[3] ) { 2.5961804389953613, -0.06132837012410164, -0.6119301915168762 }, 0.08388535318696275 },
	{ ( float[3] ) { -0.13264799118041992, 1.2842072248458862, 1.5546934604644775 }, 0.24447915574344586 },
	{ ( float[3] ) { 0.13597241044044495, 0.8917543888092041, 1.202687382698059 }, 0.1969769707958344 },
	{ ( float[3] ) { -0.14907598495483398, 1.6384907960891724, 1.2441213130950928 }, 0.2623287182554079 },
	{ ( float[3] ) { 0.992279052734375, 0.05388951301574707, -0.6508761048316956 }, 0.12264799313536288 },
	{ ( float[3] ) { -0.5784022212028503, 0.9063126444816589, 0.3831862509250641 }, 0.1905398268219135 },
	{ ( float[3] ) { -0.040377117693424225, 1.3343130350112915, 0.9407729506492615 }, 0.1520423031720309 },
	{ ( float[3] ) { 0.4423299729824066, 1.115114450454712, 1.7054131031036377 }, 0.16304635310400611 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
